ckeditor_bundle_connector:
  path: /ckeditor_bundle/connector/
  methods: ['POST', 'GET']
  controller: 'Prokl\CkEditorBundle\Controller\ConnectorController::action'

ckeditor_bundle_medialib:
  path: /ckeditor_bundle/medialib/
  methods: ['POST', 'GET']
  controller: 'Prokl\CkEditorBundle\Controller\MediaLibController::action'
