services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Инициализация битриксового события.
  ckeditor_bundle.bitrix_event_handler_init:
    class: Prokl\CkEditorBundle\Services\EventCK
    tags:
      - { name: bitrix.events.init, module: main, event: OnEpilog, method: register, sort: 0 }

  ckeditor_bundle.connector_controller:
    class: Prokl\CkEditorBundle\Controller\ConnectorController

  ckeditor_bundle.medialib_controller:
    class: Prokl\CkEditorBundle\Controller\MediaLibController
